<?php
Class Message{
    
    private $mensaje;
    
    public function __construct(){
        $this->mensaje = array(
            '010'=>'Registro Exitoso',
            '0111'=>'El campo email no tiene el formato adecuado',
            '0112'=>'El campo nombre no tiene el formato adecuado',
            '0113'=>'El campo apellido no tiene el formato adecuado',
            '0114'=>'El campo fecha de Nacimiento no tiene el formato adecuado',
            '0115'=>'El campo password no tiene el formato adecuado',
            '0116'=>'El campo Ciudad no tiene el formato adecuado',
            '0117'=>'El campo Direccion no tiene el formato adecuado',
            '0118'=>'El campo tipo de documento no tiene el formato adecuado',
            '0119'=>'El campo documento no tiene el formato adecuado',
            '012'=>'Error interno del servidor',
            '0122'=>'El email ya se encuentra asociado a un usuario',
            '020'=>'Login Exitoso',
            '021'=>'Los datos enviados no tienen el formato adecuado',
            '022'=> 'Error interno del servidor',
            '023'=> 'Login Incorrecto',
            '030'=>'Informacion retornada exitosamente',
            '031' =>'Error de autenticacion',
            '032'=>'Error interno del servidor',
            '033'=>'Error interno del servidor',
            '040'=>'Informacion retornada exitosamente',
            '041' =>'Error de autenticacion',
            '042'=>'Error interno del servidor',
            '043'=>'Error interno del servidor',
            '050'=>'Informacion retornada exitosamente',
            '051' =>'Error de autenticacion',
            '052'=>'Error interno del servidor',
            '053'=>'No existen consumos para esta cuenta',
            '060'=>'Informacion retornada exitosamente',
            '061' =>'Error de autenticacion',
            '062'=>'Error interno del servidor',
            '063'=>'No existen facturas para esta cuenta',
            '070'=>'Informacion retornada exitosamente',
            '071' =>'Error de autenticacion',
            '072'=>'Error interno del servidor',
            '073'=>'Factura inexistente',
            '080'=>'Informacion retornada exitosamente',
            '081' =>'Error de autenticacion',
            '082'=>'Error interno del servidor',
            '083'=>'Usuario inexistente',
            '090'=>'Informacion actualizada exitosamente',
            '091' =>'Existen datos enviados que no poseen el formato adecuado',
            '092'=>'Error interno del servidor',
            '093'=>'Usuario Inexistente',
            '094' =>'Error de autenticacion',
            '100'=>'Informacion actualizada exitosamente',
            '101' =>'Los datos enviados no contienen el formato adecuado',
            '102'=>'Error interno del servidor',
            '103'=>'Cuenta Inexistente',
            '104' =>'Error de autenticacion',
            '110'=>'Ciudades retornadas exitosamente',
            '111' =>'Error de autenticacion',
            '112'=>'Error interno del servidor',
            '113'=>'Departamento inexistente',
            '114'=>'El departamento enviado no tiene el formato adecuado',
            '120'=>'Departamentos retornados exitosamente',
            '121' =>'Error de autenticacion',
            '122'=>'Error interno del servidor',
            '123'=>'Pais inexistente',
            '124'=>'El pais enviado no tiene el formato adecuado',
            '130'=>'Informacion actualizada exitosamente',
            '131' =>'Error de autenticacion',
            '132'=>'Error interno del servidor',
            '140'=>'Confirmacion realizada exitosamente',
            '141'=>'Codigo Incorrecto',
            '142'=>'Error interno del servidor',
            '150'=>'Inicio de recuperacion finalizado',
            '151'=>'El email no es correcto o posee un formato inadecuado',
            '152'=>'El email ingresado no corresponde a un usuario registrado',
            '153'=>'Error interno del servidor',
            '154'=>'Ya se ha generado el reinicio de password para este usuario',
            '160'=>'Reinicio de password exitoso',
            '161'=>'Los datos enviados no poseen el formato adecuado',
            '162'=>'Error interno del servidor',
            '163'=>'Ya no es posible reiniciar el password'
            
        );
    }
    
    public function getMessage($codigo){
        return $this->mensaje[$codigo];
    }
}